name: adaptive_spinner
description: A circular progress indicator, scalable and adaptive to multiple platforms
version: 1.0.0
homepage: https://github.com/TheFe91/adaptive_spinner

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0

flutter:
  uses-material-design: true