name: adaptive_spinner
description: A circular progress indicator, scalable and adaptive to multiple platforms
version: 0.0.1
author: Alessandro Defendenti
homepage: https://github.com/TheFe91/adaptive_spinner

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: